/**
 * Annotation format exporters — pure functions, no DOM, testable in Node.
 *
 * Internal box format (image-pixel coordinates):
 *   { x, y, w, h, cls }   x,y = top-left corner, cls = class index
 *
 * Dataset shape passed in:
 *   images:  [{ name, width, height, boxes: [box] }]
 *   classes: [{ name, color }]
 */
const Exporters = (() => {
  /**
   * YOLO: one .txt per image, each line "cls cx cy w h" with all four box
   * numbers normalized to 0..1 (center-based). This is the format Ultralytics
   * YOLO trainers expect. https://docs.ultralytics.com/datasets/detect/
   */
  function yoloLine(box, imgW, imgH) {
    const cx = (box.x + box.w / 2) / imgW;
    const cy = (box.y + box.h / 2) / imgH;
    const w = box.w / imgW;
    const h = box.h / imgH;
    const f = (n) => Math.min(1, Math.max(0, n)).toFixed(6);
    return `${box.cls} ${f(cx)} ${f(cy)} ${f(w)} ${f(h)}`;
  }

  function yoloTextFor(image) {
    return image.boxes.map((b) => yoloLine(b, image.width, image.height)).join('\n');
  }

  /** Returns the list of files (name/text) that make up a YOLO export bundle. */
  function yoloFiles(images, classes) {
    const files = images
      .filter((im) => im.boxes.length > 0)
      .map((im) => ({
        name: `labels/${im.name.replace(/\.[^.]+$/, '')}.txt`,
        text: yoloTextFor(im),
      }));
    files.push({ name: 'classes.txt', text: classes.map((c) => c.name).join('\n') });
    files.push({
      name: 'data.yaml',
      text:
        `# YOLO dataset config generated by MineLabeler\n` +
        `nc: ${classes.length}\n` +
        `names: [${classes.map((c) => JSON.stringify(c.name)).join(', ')}]\n`,
    });
    return files;
  }

  /**
   * COCO: single JSON with images[], annotations[], categories[].
   * bbox is [x, y, width, height] in absolute pixels (COCO convention).
   * https://cocodataset.org/#format-data
   */
  function coco(images, classes) {
    const out = {
      info: { description: 'MineLabeler export', date_created: new Date().toISOString() },
      images: [],
      annotations: [],
      categories: classes.map((c, i) => ({ id: i, name: c.name, supercategory: 'ordnance' })),
    };
    let annId = 1;
    images.forEach((im, imgId) => {
      out.images.push({ id: imgId, file_name: im.name, width: im.width, height: im.height });
      im.boxes.forEach((b) => {
        out.annotations.push({
          id: annId++,
          image_id: imgId,
          category_id: b.cls,
          bbox: [b.x, b.y, b.w, b.h],
          area: b.w * b.h,
          iscrowd: 0,
        });
      });
    });
    return out;
  }

  /** Parse a COCO JSON back into {classes, byName: {filename: [box]}}. */
  function parseCoco(json) {
    const cats = [...(json.categories || [])].sort((a, b) => a.id - b.id);
    const catIndex = new Map(cats.map((c, i) => [c.id, i]));
    const classes = cats.map((c) => c.name);
    const imgById = new Map((json.images || []).map((im) => [im.id, im.file_name]));
    const byName = {};
    for (const a of json.annotations || []) {
      const name = imgById.get(a.image_id);
      if (!name) continue;
      const [x, y, w, h] = a.bbox;
      (byName[name] = byName[name] || []).push({
        x, y, w, h, cls: catIndex.get(a.category_id) ?? 0,
      });
    }
    return { classes, byName };
  }

  return { yoloLine, yoloTextFor, yoloFiles, coco, parseCoco };
})();

if (typeof module !== 'undefined') module.exports = Exporters;
